---
name: Text-SimpleTable-AutoWidth
abstract: 'Simple Eyecandy ASCII Tables with auto-width selection'
version: 0.03
author:
  - Oleg Kostyuk <cub@cpan.org>
license: perl
distribution_type: module
requires:
    Moose: 0.78
    Text::SimpleTable: 0.03
recommends:
build_requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: 'manually ;)'
no_index:
  directory:
    - inc
    - t

